### ISSUE TITLE
Issue with Parsing of /all Chat when using Zomboid Discord > Chat Integration

### ISSUE THREAD

**Issue by GizmoNomical** [omarkmu/pz-omichat#9]
### Bug Description

Hello,  

     First off, great mod!  Really feature rich and complete to start with.  I only have one small issue, and after digging through your documentation I am a bit stumped at how to fix it.

     I run a dedicated server and use the standard Discord Integration to post in-game /all chat to a Discord Channel.  Your mod still sends the /all chat to the channel, but as the text is parsed it is prefix/suffixed with invisible characters.

This is the character that shows up:  ￿

I am assuming it is some sort of mod data interpretation for how the different chat elements display in the game itself, but for whatever reason it comes across as garbled special characters in the discord.

It wouldn't be such an issue, except it really convolutes the ability to read the in-game chat from the discord channel.

Included is an image of how the Discord Looks, with an example of before the mod was added, and after the mod was added.

I would appreciate any insight into this and if their is a way to fix it on my end.  Thank you very much!

![image](https://github.com/omarkmu/pz-omichat/assets/82304247/0399bfd4-639e-4b06-a19e-c67d14913dec)

### Additional Information

Server Host/Admin

**Comment by omarkmu** [comment]
Hey, thanks for the report! You're right that those characters are for mod functionality. They're characters that are invisible ingame, so I use them for formatting.

I'll look into whether it's possible to remove those characters before the message is sent to Discord. I fear it won't be since the Discord integration is Java-side, but hopefully there's a way.

**Comment by omarkmu** [comment]
I just looked into it a bit and it seems like getting rid of these characters before sending to Discord would only be possible via a Java mod. Cleaning up the logs is also possible, with the same caveat. Fortunately, though, replacing the files would only be necessary on the server since these are server-side methods.

I'll see about setting up those optional java overrides. I haven't used the game's Discord integration myself, so it may take a while for those to be ready and tested; uninstalling for now is totally reasonable!

For reference, the necessary methods to override would be `GeneralChat.sendMessageToChatMembers` and `ChatServer.processMessageFromPlayerPacket`.

**Comment by omarkmu** [comment]
It ended up being more straightforward than I anticipated. I marked the PR as a draft because I'd still like to do some testing on a real dedicated server, rather than just the Host menu, before I'm confident that everything's working as expected. That said, there were no problems during initial testing so I anticipate being able to mark that as done soon! The documentation will also be [updated](https://github.com/omarkmu/pz-omichat/blob/078d80905eb506db24ceefc4fc4cd9560e489822/docs/user-guide/java-mods.md) to include instructions for installation of these optional Java mods.

**Comment by GizmoNomical** [comment]
What an absolute badass.  Haha.  I'm sure that this will be a worthy addition for server hosts, as I assume anyone doing RP with others is going to be running a dedicated server.  Let me know if I can help test the mod, as it will be so nice to endorse that on our server for our RPers to use fully!

Thanks!

**Comment by omarkmu** [comment]
Thanks for the offer to help out with testing 😄 That shouldn't be necessary, though—I've just finished testing on a dedicated server, and I'm confident enough to go ahead with this fix! I'm going to merge the PR in a moment, which will close this issue. You'll be able to find the Java mods in the [Releases](https://github.com/omarkmu/pz-omichat/releases).

If anything isn't working as expected, please feel free to reopen the issue. Thanks again for taking the time to report this!

**Comment by GizmoNomical** [comment]
I will be testing the java mods when our server restarts in about 20 minutes.  I'll let you know if everything works as intended.

**Comment by GizmoNomical** [comment]
> Thanks for the offer to help out with testing 😄 That shouldn't be necessary, though—I've just finished testing on a dedicated server, and I'm confident enough to go ahead with this fix! I'm going to merge the PR in a moment, which will close this issue. You'll be able to find the Java mods in the [Releases](https://github.com/omarkmu/pz-omichat/releases).
> 
> If anything isn't working as expected, please feel free to reopen the issue. Thanks again for taking the time to report this!

Looks like I sent my last message right as yours came in.  I'll wait for the release, unless the files were unchanged.

**Comment by omarkmu** [comment]
There was one change to apply the same thing to the `DebugLog` files that I applied to the `chat` log files; I missed that the first time around. I just created the [release](https://github.com/omarkmu/pz-omichat/releases/tag/41.78.16-java), which has the latest files.

**Comment by GizmoNomical** [comment]
Hello again.

    Upon initial testing, the Discord Channel text shows up to be clean as it should now.

But the Server Console shows both the original text with ??? hidden characters for all player ID's / Chat Numbers, and then a duplicate message below that, without the characters.  Included is a screenshot showing the issue.

![image](https://github.com/omarkmu/pz-omichat/assets/82304247/d64ddf56-16dc-4d32-8f5a-555d69351d24)

**Comment by omarkmu** [comment]
That's strange, I didn't see that in my testing. Did you replace both files?

Unfortunately I won't be able to take another look until tomorrow evening at the earliest, but I'm glad to hear the Discord part is working as expected.

**Comment by GizmoNomical** [comment]
Here is the Chat log file.  And yes, I replaced both files.  Created .BAK of the originals, then copied in the new java classes.

[18-03-24_21-11-12_chat.txt](https://github.com/omarkmu/pz-omichat/files/14645287/18-03-24_21-11-12_chat.txt)
[18-03-24_21-17-03_client chat Buford T Justice.txt](https://github.com/omarkmu/pz-omichat/files/14645290/18-03-24_21-17-03_client.chat.Buford.T.Justice.txt)

**Comment by omarkmu** [comment]
Took a quick look at this just now. I had seen these debug log calls in `ChatBase`, but didn't replace them because I incorrectly assumed they were client-side (for some reason). It turns out I should've accepted your offer to test it out; the reason I wasn't seeing this log message on my end is because it's only sent *if other players are present*. I was testing with just myself.

I've attached a `.zip` with a new `.class` file that should replace `zombie/chat/ChatBase.class`. The other two are the same. If you don't mind, please let me know whether this resolves the issue; I'll add an updated release if it does. Thanks!

[java.zip](https://github.com/omarkmu/pz-omichat/files/14651102/java.zip)

**Comment by omarkmu** [comment]
Also, a note regarding the `client chat` log: this will continue to have invisible characters, because it's client-side. It would be possible to remove the invisible characters here by modifying `ChatManager`, but players would have to replace the file. I'd prefer to have the optional Java mods be server-side only.

**Comment by GizmoNomical** [comment]
I'll test it out here in a few and let you know how its working.

I figure in almost all use cases, these issues would only be bothering a server host/admin, since most clients are there just to log in, and play, even if they are deep into the roleplay aspects.  No real need at all for the client to have to change anything.

Thanks again for all your help, really appreciate it!

**Comment by GizmoNomical** [comment]
The last changes seemed to have resolved the issue.  I will test again when there are more players on the server, but as far as I can tell the issue is resolved!  Thank you!

**Comment by omarkmu** [comment]
Great, thank you!
